[build]
  base = “packages/site/”
  functions = "src/functions/"
  command = "npm run build"


[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200


[[redirects]]
  from = '/email/*'
  to = '/email/:splat'
  status = 200


[[redirects]]
  from = '/agreement/*'
  to = '/agreement/:splat'
  status = 200

 [[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200




